### ISSUE TITLE
Image Thread

### ISSUE THREAD

**Issue by FIN443** [boostcampaitech4lv23cv3/level2_semanticsegmentation_cv-level2-cv-16#1]
![7645ad37-9853-4a85-b0a8-f0f151ef05be](https://user-images.githubusercontent.com/70796031/214523079-7066fa79-d8c8-449a-b46a-2df376f67a65.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214524350-2d7bc75b-bb26-41a8-9f82-67841bbc68d9.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214527673-84e23752-b231-4b6f-abb8-b940097f0762.png)

**Comment by revanZX** [comment]
![image](https://user-images.githubusercontent.com/25689849/214527798-e1af285d-9c5c-4199-a4b6-d8162ec24d20.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214528789-16cb5030-34b0-4d59-b65c-ee605fa9ebdd.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214529354-7e0b606b-ef42-41e5-b19b-431af85a9516.png)

**Comment by arislid** [comment]
![image](https://user-images.githubusercontent.com/46767966/214523896-9884eb65-1b5e-48a1-bcf6-63e365c1fdd6.png)
![image](https://user-images.githubusercontent.com/46767966/214525567-da6530dc-e983-4532-a14e-28beeb98575f.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214537394-c87dbf48-7e6a-4886-b7a2-63a65def29ee.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214734345-8c7eb577-127d-4e3c-8032-c1d03327f77f.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/215421290-5025193b-bc9b-411b-b5a8-27054588091c.png)
